### ISSUE TITLE
Move requirements.txt to examples directory

### ISSUE THREAD

**Issue by cemaybe** [SAP/document-classification-client#26]
@manuel-berning

**Comment by manuel-berning** [comment]
Hmm. Interesting proposal. Currently this would break the repo2docker (e.g. mybinder) way to consume this repo.
The file you mentioned is used as a configuration file in repo2docker to install python dependencies:
https://repo2docker.readthedocs.io/en/latest/config_files.html
Could of course all install these requirments in notebook itself (but then runtime.txt similar proposals could be discussed).

**Comment by manuel-berning** [comment]
I just checked again an maybe it would be good to motivate why you would want to move it.
AFAIK the requirements for the (client library) python package are defined in setup.py and I do not see an issue having the requirements in the top level if it does not interfere with other workflows/usages of the repo.

**Comment by cemaybe** [comment]
Resolved by https://github.com/SAP/document-classification-client/commit/f24d9eb04911097f4f80cecc98484d5d987466c1
